<script setup></script>

<template>
  <div class="app">
    <a-typography-title>IPTables Debugger</a-typography-title>
    <div class="content">
      <router-view v-slot="{ Component }">
        <Suspense timeout="0">
          <component :is="Component" />
          <template #fallback>
            <div class="loading">
              <a-spin />
            </div>
          </template>
        </Suspense>
      </router-view>
    </div>
    <div class="footer">@Generated by trungvd</div>
  </div>
</template>

<style scoped>
.app {
  margin: 20px 60px;
}
.content {
  min-height: 600px;
}
.footer {
  text-align: center;
  padding: 15px;
}
</style>
